# Generated by Django 3.0.6 on 2020-05-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_demo', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
