# Generated by Django 3.0.6 on 2020-05-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_demo', '0005_auto_20200506_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_token',
            field=models.CharField(blank=True, max_length=9, verbose_name='username'),
        ),
    ]
