# Generated by Django 3.0.6 on 2020-05-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_demo', '0006_user_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_token',
            field=models.CharField(blank=True, max_length=9, verbose_name='activation code'),
        ),
    ]
